# Generated by Django 5.1.7 on 2025-03-25 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_customuser_bio_remove_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveIntegerField()),
                ('reps', models.PositiveIntegerField()),
                ('weight', models.FloatField(blank=True, help_text='Weight in kilograms', null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='home.gymexercise')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('activity_type', models.CharField(choices=[('R', 'Running'), ('G', 'Gym Session')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('distance', models.FloatField(blank=True, help_text='Distance in kilometers', null=True)),
                ('pace', models.CharField(blank=True, help_text='Pace in min/km, e.g., 5:30', max_length=5, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='gymexercise',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='home.workouttemplate'),
        ),
    ]
