# Generated by Django 5.1.7 on 2025-04-03 13:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_sessionexercise_sessionset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutsession',
            name='completed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
