# Generated by Django 5.1.7 on 2025-04-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_customuser_level_customuser_xp_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionset',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
